[package]
name = "angea"
version = "0.0.2"
edition = "2018"

[dependencies]
dbus = "^0.9.3"
libc = "^0.2.99"
nix = "^0.20.0"
unshare = "^0.7.0"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
debug = 0
