[package]
name = "angea"
version = "0.0.3"
edition = "2018"

[dependencies]
libc = "^0.2.99"
libdbus-sys = "0.2.1"
nix = "^0.22.1"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
debug = 0
