[package]
name = "angea"
version = "0.0.3"
edition = "2018"

[dependencies]
dbus = {version="^0.9.3", features=["no-string-validation"]}
libc = "^0.2.99"
nix = "^0.22.1"

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
codegen-units = 1
debug = 0
