[package]
name = "angea"
version = "0.0.5"
edition = "2021"

[dependencies]
libc = "^0.2.99"
libsystemd-sys = "0.9.0"
nix = "^0.23.0"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
codegen-units = 1
debug = 0
